---
title: "Day 2"
output: github_document
---

```{r packages}
library(tidyverse)
```

```{r read}
input <- read_table(here::here("Inputs", "input_02.txt"), col_names = c("O", "Y"), skip_empty_rows=FALSE)
input
```

A for rock, B for Paper, C for Scissors

Believe X for rock, Y for paper, and Z for Scissors


```{r solutionpart1}

score_shape <- function(x){
  case_when(
    x %in% c("X", "A")~1,
    x %in% c("Y", "B")~2,
    x %in% c("Z", "C")~3
  )
}

name_shape <- function(x){
  case_when(
    x %in% c("X", "A")~"rock",
    x %in% c("Y", "B")~"paper",
    x %in% c("Z", "C")~"scissors"
  )
}

game_score <- function(me, you){
  case_when(
    me==you~3, #draw
    (me %% 3) == ((you + 1) %% 3)~6, #win
    TRUE ~ 0 #lose
  )
}

GameScores <- input %>%
  mutate(
    ShapeScoreO=score_shape(O),
    ShapeScoreY=score_shape(Y),
    ShapeO=name_shape(O),
    ShapeY=name_shape(Y),
    GameScore=game_score(ShapeScoreY, ShapeScoreO),
    TotScore=ShapeScoreY+GameScore
    
  ) 

GameScores

GameScores %>% pull(TotScore) %>% sum()
```


```{r solutionpart2}
GameScores2 <- input %>%
  mutate(
    ShapeScoreO=score_shape(O),
    ShapeScoreY=case_when(
      Y=="X"~ if_else(ShapeScoreO-1>0, ShapeScoreO-1, 3), #you need to lose
      Y=="Y"~ShapeScoreO, #draw
      Y=="Z"~ if_else(ShapeScoreO+1<=3, ShapeScoreO+1, 1), #you need to win
    ),
    GameScore=case_when(
      Y=="X"~ 0, #lose
      Y=="Y"~3, #draw
      Y=="Z"~ 6 #win
    ),
    TotScore=ShapeScoreY+GameScore
  )

GameScores2

GameScores2 %>% pull(TotScore) %>% sum()
```

