---
title: "Day 3"
output: github_document
---

```{r packages}
library(tidyverse)
```

```{r read}
input <- read_table(here::here("Inputs", "input_03.txt"), col_names = c("contents"), skip_empty_rows=FALSE)
input
```



```{r solutionpart1}

priority <- tibble(
  common=c(letters, LETTERS),
  priority=1:52
)

puzz1 <- input %>%
  mutate(
    len = str_length(contents),
    Comp1=str_sub(contents, 1, len/2),
    Comp2=str_sub(contents, len/2+1, len),
    common=str_match(Comp1, str_c("[",Comp2, "]"))
  ) %>%
  left_join(priority, by="common")

puzz1 %>% pull(priority) %>% sum()

```

```{r solutionpart2}

puzz2 <- input %>%
  mutate(
    Group=ceiling((row_number())/3),
    Pers=str_c("Pers", (row_number()-1) %% 3)
  ) %>%
  pivot_wider(id_cols=Group, names_from=Pers, values_from = contents) 

priority_v <- 1:52
names(priority_v) <- c(letters, LETTERS)

priority_sum <- 0
for (i in 1:nrow(puzz2)){
  Pers0 <- puzz2 %>% slice(i) %>% pull(Pers0)
  Pers1 <- puzz2 %>% slice(i) %>% pull(Pers1)
  Pers2 <- puzz2 %>% slice(i) %>% pull(Pers2)
  
  commlet <- Pers0 %>% str_match_all(str_c("[", Pers1, "]")) %>% 
    .[[1]] %>% as.vector() %>%
    unique() %>% str_c(collapse="") %>%
    str_match_all(str_c("[", Pers2, "]")) %>%
    .[[1]] %>% as.vector()
  
  priority_sum <- priority_sum+ priority_v[commlet]
}

priority_sum

```

